// 'use client' directive removed

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Supabase imports removed
import ClientLayoutWrapper from "./ClientLayoutWrapper"; // Import the new wrapper

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// useSession import removed

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // session hook removed

  return (
    <html lang="en">
      {/* SessionContextProvider removed */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navigation moved to ClientLayoutWrapper */}
        <ClientLayoutWrapper> {/* Use the client wrapper */}
          {children}
        </ClientLayoutWrapper>
      </body>
      {/* SessionContextProvider removed */}
    </html>
  );
}
